language: scala

scala:
  - 2.11.8
  - 2.12.1

env:
  - JDK=oraclejdk8

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
  - mkdir -p $HOME/.bintray $HOME/.ssh
  - openssl aes-256-cbc -K $encrypted_40c69c371628_key -iv $encrypted_40c69c371628_iv -in .travis/credentials.enc -out $HOME/.bintray/.credentials -d
  - openssl aes-256-cbc -K $encrypted_40c69c371628_key -iv $encrypted_40c69c371628_iv -in .travis/release-key.enc -out $HOME/.ssh/id_rsa -d

deploy:
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
      scala: 2.12.1
